# Generated by Django 5.2.5 on 2025-08-15 15:02

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do aluno')),
                ('ra', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(code='invalid_ra', message='RA must be 8 digits.', regex='^a\\d{7}$')], verbose_name='RA do aluno')),
                ('email', models.EmailField(max_length=100, verbose_name='Email do aluno')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do professor')),
                ('email', models.EmailField(max_length=100, verbose_name='Email do professor')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroPontoAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data e hora do registro')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=10, verbose_name='Tipo de registro')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_de_ponto.aluno', verbose_name='Aluno')),
            ],
        ),
    ]
